# Generated by Django 5.0.4 on 2024-04-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='expiry_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='expiry_at',
            field=models.DateField(null=True),
        ),
    ]
