# Generated by Django 5.0.4 on 2024-04-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_budget_expiry_at_alter_subscription_expiry_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='amount',
            field=models.FloatField(null=True),
        ),
    ]
