# Generated by Django 5.0.4 on 2024-04-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_expense_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='expiry_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='expiry_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
