# Generated by Django 5.0.4 on 2024-04-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_budget_expiry_at_alter_subscription_expiry_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='tags',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='tags',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='income',
            name='income_type',
            field=models.CharField(max_length=200),
        ),
    ]
