# Generated by Django 5.0.4 on 2024-04-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='total_balance',
            field=models.FloatField(default=0),
        ),
    ]
