# Generated by Django 5.0.4 on 2024-04-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_total_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='number_of_transactions',
            field=models.IntegerField(default=0),
        ),
    ]
