# Generated by Django 5.0.4 on 2024-04-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_number_of_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='number_of_budgets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='number_of_subscriptions',
            field=models.IntegerField(default=0),
        ),
    ]
