version: '3.8'

services:
  postgres:
    image: postgres:16.2
    container_name: postgres_container
    environment:
     POSTGRES_DB: kotlin_app_db
     POSTGRES_USER: admin
     POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8.2
    container_name: pg-admin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "80:80"

volumes:
  pg-data: